### ISSUE TITLE
AUR pkg

### ISSUE THREAD

**Issue by makew0rld** [makeworld-the-better-one/gemget#15]
See makeworld-the-better-one/amfora#58

**Comment by dalz** [comment]
I published a PKGBUILD https://aur.archlinux.org/packages/gemget, it looks fine to me but I know very little about Go so you may want to check it.

**Comment by makew0rld** [comment]
Thanks, that's great!  I would also advise looking at the Amfora [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=amfora) too though, as the makefiles/build process for these projects are nearly identical.

Why not match the PKGBUILD of Amfora and not use `make`, but just `go build`? And specify the required variables with `-X`. For example, add this to the end of `GOFLAGS`:

```
-X main.builtBy=gemget-AUR -X main.commit=6262222a6c35d98e1e15fe43cd3a0b136b078949
```

Note you will have to update that commit value on every release.

Also I am wondering why you have this line:

```shell
sed -i '/^GIT[VC]/d' Makefile
```

In any case, if you stop using the Makefile you won't need to have it.

**Comment by dalz** [comment]
> Why not match the PKGBUILD of Amfora and not use make, but just go build?

I figured it'd be better to stay as close as I could to the upstream build process, for instance amfora's PKGBUILD lacks `GO111MODULE=on CGO_ENABLED=0` which the Makefile has. I don't know if they're actually needed though, and I'm ready to switch to calling `go build` directly if you'd prefer that.

> Also I am wondering why you have this line:
> `sed -i '/^GIT[VC]/d' Makefile`

The source tarball is not a git repo, so
```
GITV != git describe --tags
GITC != git rev-parse --verify HEAD
```
would spit out some errors, I added the `sed` to silence them out.

**Comment by makew0rld** [comment]
`CGO_ENABLED=0` is not needed. As for `GO111MODULE=on`... that's a good question, I was wondering that myself. The Arch Wiki didn't seem to know either. I will leave a comment on the Amfora package to ask about that, and I'll also mention @pboyd to see what he thinks. (He's the maintainer of that package.)

> I added the `sed` to silence them out.

Ah ok.

---

One thing you've missed is the `BUILDER` env var, which should be something like `gemget-AUR`. Other than that, this package is good then! Thanks. And we'll see what @pboyd says about `GO111MODULE`.

Also, if you could add me as a maintainer, like I am on the Amfora package, that would be appreciated. My username is `makeworld`.

**Comment by dalz** [comment]
> BUILDER env var

Oh right I forgot that, it's fixed now.

> add me as a maintainer

:+1:

**Comment by makew0rld** [comment]
Thanks! I'll add this to the README.

**Comment by pboyd** [comment]
The simple answer is that `GO111MODULE=on` wasn't needed to build Amfora, so I left it off. [Go's default behavior](https://golang.org/ref/mod#mod-commands) is to use "auto", which is the same as "on" when there's a go.mod (and there is).

@makeworld-the-better-one, feel free to correct me, but I imagine that's in the instructions in case the user has it set in their environment? The build would certainly fail if the value is "off", and the manual value always works, so this seems logical. But AUR builds are isolated enough that setting it explicitly is unnecessary. I don't see any harm to leaving it in though.

**Comment by makew0rld** [comment]
If the AUR build environment doesn't carry over the user's environment variables than we're good. And that makes sense, I just wasn't sure if that was the case. I'm used to having to specify `GO111MODULE=on` in my Makefiles and READMEs to compensate for people's potentially bad setups.

Thanks! Seems like both packages are good then.
