### ISSUE TITLE
Download all files in subdirectory?

### ISSUE THREAD

**Issue by francesmothrock** [makeworld-the-better-one/gemget#26]
Is it possible to download all the gmi files in subdirectories, like a gemlog, or is it limited to one gmi at a time? I apologize if this is a silly question, I am a CLI newbie.

Are there usage examples for this sort of thing?

**Comment by makew0rld** [comment]
Downloading from links on a page is not supported. You would have to download the page, parse out the links yourself (by hand or with a script), and then get gemget to download those links.
