### ISSUE TITLE
Recursive download?

### ISSUE THREAD

**Issue by d47081** [makeworld-the-better-one/gemget#28]
I want to make local website copy (e.g. curl mirror), is it possible?

**Comment by makew0rld** [comment]
No. Gemget does not parse the data it receives, so it can't currently extract links to crawl them again. This is exterior functionality you would have to build yourself. As gemget is in [maintenance mode](https://github.com/makew0rld/gemget?tab=readme-ov-file#project-status), I will not be adding this feature.

**Comment by d47081** [comment]
Well, I have implemented this feature in [gemini-dl](https://github.com/YGGverse/gemini-dl)
