### ISSUE TITLE
Provide an option to show the Gemini server response header in stdout

### ISSUE THREAD

**Issue by LukeEmmet** [makeworld-the-better-one/gemget#4]
It can sometimes be useful to see the Gemini server response, even if gemget is succesful, for example to determine the mime type/charset etc. A -h flag could be used as an option to show this output.

Related to this, it would be helpful to better label the output to distinguish info/error/header message. Both changes would assist a human user or automating client wishing to make use of the header info.

I attach an edit to gemget.go which implements this for your consideration. 
[gemget.zip](https://github.com/makeworld-the-better-one/gemget/files/4848228/gemget.zip)

**Comment by makew0rld** [comment]
Alright, I've made some changes based on your code. You should look at 8f0f7d855a64a4b82d1f68ced03c57f08e7a170b and 6de90f45c595cf0a99c3dc5d0ebb486717f3b4be

I changed the way the new header feature is printed. My code only prints the final header, so if there is a redirect, it doesn't print the redirect header, but the final one instead, once content is found. Does that still work for you?

I will be releasing a new version of gemget once you take a look at these changes, and I'd appreciate if GemiNaut updates to use it :)

**Comment by LukeEmmet** [comment]
thanks for the update. 

I do need the intermediate headers as well (as per my submission above), for example when redirecting, I need to know what URL is redirected to so that I can wire up the URLs in the final document with respect to the correct base URL.

Also the headers aren't shown in some situations. For example when input is requested, no header is shown, even if --header is on. I am using the header to request input from the user, then the request is made again with the query.

I'll try to integrate it as is to check it works, and await the update. Yes I'm happy to use the official build in GemiNaut.

thanks

**Comment by makew0rld** [comment]
Alright, it's not a big deal to me either. I've just committed a change that prints the header for each request. Let me know if this works well for you, and I'll close the issue and release.

Edit: You can download a Windows 386 binary of the latest change [here](https://gofile.io/d/pMMjxn).

**Comment by LukeEmmet** [comment]
I just spotted your new response thanks - I'll try this.

I just tried it - works perfectly. Many thanks! 👍

**Comment by makew0rld** [comment]
Great, you're welcome! I will make a new release in a bit.

**Comment by makew0rld** [comment]
gemget v1.3.0 has been released with these changes, and binaries are uploading now. Thanks again for your suggestions!
