### ISSUE TITLE
provide a max-limit option for downloads

### ISSUE THREAD

**Issue by LukeEmmet** [makeworld-the-better-one/gemget#6]
Gemini has no concept of Content-Length, so it is always unknown how big the download is. There could be a useful option in gemget to specify the maximum size to be downloaded for each passed URL. If there limit were reached, an error message should be added to stderr (and maybe any partial download deleted?)

**Comment by makew0rld** [comment]
716950b has added this feature, it will be in the next release which is coming soon, possibly today. You can set it with the `-m` or `--max-size` flag.

> an error message should be added to stderr (and maybe any partial download deleted?)

I opted to go for an info message, that should be fine? And yes, I delete the partial file.
