### ISSUE TITLE
provide a server download timeout option

### ISSUE THREAD

**Issue by LukeEmmet** [makeworld-the-better-one/gemget#7]
Gemini has no concept of Content-Length, so we dont know when the server might or might not be done.

It would be useful to have an option to specify the maximum time before the download is abandoned. In conjunction with the max download size option, callers can put limits in the amount of content to be downloaded before the connection is abandoned.

If the download time is exceeded, an error is added to std err (and maybe any partial download is deleted)

**Comment by makew0rld** [comment]
Note: Use a goroutine that closes the response if it's open after the max time.

**Comment by makew0rld** [comment]
c4ce2b1 adds this feature, with the flags `-t` and `--max-time` which allow you to specify a timeout in seconds.

> If the download time is exceeded, an error is added to std err (and maybe any partial download is deleted)

I changed this to an Info string, and yes, partial downloads are deleted.
